# Generated by Django 4.0.6 on 2022-09-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0003_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='category.jpg', upload_to=''),
        ),
    ]
